### ISSUE TITLE
Deserializing Architecture json file

### ISSUE THREAD

**Issue by MajesticKhan** [tensorflow/adanet#102]
NOTE: I am running Adanet on windows 10 using python 3.5.2

Has anybody ran into this error: `TypeError: the JSON object must be str, not 'bytes'`?
I am currently debugging the code and this is what I have so far:

`gfile.read()` outputs  bytes instead of string. This causes an error when `_Architecture.deserialize()` uses json.loads() which requires a string object.

https://github.com/tensorflow/adanet/blob/cb9c718c35b5d16e05b51f15040b4b448798c5d2/adanet/core/estimator.py#L1145-L1146

https://github.com/tensorflow/adanet/blob/cb9c718c35b5d16e05b51f15040b4b448798c5d2/adanet/core/architecture.py#L103-L119

**Comment by cweill** [comment]
@MajesticKhan: We only currently test on Linux machine with CI. If you find a fix, feel free to send a PR and I'll review it.

**Comment by MajesticKhan** [comment]
Got it. 
Let me dig a little deeper into the issue and start testing out other examples to check if the issue is on my side, if not I will create a PR with the fix. I'll keep you updated through gitter

**Comment by WillianPaiva** [comment]
I'm trying to train on using cloud ML engine and I'm getting the same error, I'm not sure it is windows related

**Comment by MajesticKhan** [comment]
Okay, the serializing issue is a simple fix, `gfile.read().decode()`. However, there is another issue when temp_model_dir folder is still being used by an initial model preventing files from being deleted. I hacked my way around this by creating mutiple temp_model_dir folders and not deleting them. After that, it was smooth sailing. 

Currently, I'm creating a simple script to test both on windows and linux. After that, I'll figure out how to deal with the folder issue and submit a pr with the fixes.

**Comment by MajesticKhan** [comment]
Sorry accidentally clicked on closed.

@WillianPaiva What version of numpy are you using? When I reinstalled Adanet, it reverted back to the previous numpy to 1.15 which prevented me from running a simple script that trains a dnn model. Going back to numpy 1.16.3 allowed me to run the script again

**Comment by cweill** [comment]
> When I reinstalled Adanet, it reverted back to the previous numpy to 1.15

I think our dependency requirements were hard-coded to be too strict, so I'll create a commit to loosen those requirements. Did upgrading to numpy 1.16.3 fix any of the other issues you were experiencing?

**Comment by MajesticKhan** [comment]
@cweill, I reinstalled Adanet and it defaulted to installing numpy 1.15.4 which still caused errors. I would consider strictly upgrading to match the numpy version that Tensorflow 1.13 is using which is numpy-1.16.3

**Comment by MajesticKhan** [comment]
@cweill This is the script that I will be using to test both on Linux and Windows 10. I copied it from my repository for easier viewing:

```python
#----------------------------------------------------------------Import Libraries
import tensorflow as tf
import pandas as pd
import adanet
tf.logging.set_verbosity("INFO")
#----------------------------------------------------------------


#----------------------------------------------------------------State meta data
Features  = ['SepalLength', 'SepalWidth',
             'PetalLength', 'PetalWidth']
TRAIN_URL = "http://download.tensorflow.org/data/iris_training.csv"
TEST_URL  = "http://download.tensorflow.org/data/iris_test.csv"
#----------------------------------------------------------------


#----------------------------------------------------------------Create feature numeric columns
feature_columns = []
for key in Features:
    feature_columns.append(tf.feature_column.numeric_column(key=key))
#----------------------------------------------------------------


#----------------------------------------------------------------Define dataset input function
def input_fn(file_path, batch_size, epoch, y_name='Species'):

    train    = pd.read_csv(file_path, names = Features + [y_name], header = 0)
    labels   = train.pop(y_name)
    features = train

    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat(epoch).batch(batch_size)

    # Return the dataset.
    return dataset
#----------------------------------------------------------------


#----------------------------------------------------------------Create the estimator
config = tf.estimator.RunConfig(
  model_dir              = "Path to Directory",
)

# Define the model head for computing loss and evaluation metrics.
head = tf.contrib.estimator.multi_class_head(n_classes=3)

# Learn to ensemble linear and neural network models.
estimator = adanet.AutoEnsembleEstimator(
    head = head,
    candidate_pool = {
        "linear":
            tf.estimator.LinearEstimator(
                head=head,
                feature_columns=feature_columns),
        "dnn":
            tf.estimator.DNNEstimator(
                head=head,
                feature_columns=feature_columns,
                hidden_units=[10,10])},
    max_iteration_steps=50)
#----------------------------------------------------------------


#----------------------------------------------------------------Execute
# Train the Model.
estimator.train(
    input_fn = lambda: input_fn(TRAIN_URL,10, epoch = None),
    max_steps = 100)

# Evaluate the model.
eval_result = estimator.evaluate(
    input_fn = lambda: input_fn(TEST_URL,10, epoch = 1))
#----------------------------------------------------------------


#----------------------------------------------------------------Sources
# https://github.com/tensorflow/models/tree/master/samples/core/get_started
#----------------------------------------------------------------
```

**Comment by cweill** [comment]
@MajesticKhan That script looks good to me. Keep us posted. And feel free to send a PR with a fix for reading the architecture JSON file.

**Comment by MajesticKhan** [comment]
@cweill Working on that pr now...

Two things:

1.) On Linux, I confirmed that the json issue is affected on linux as well
2.) The numpy version should be 1.16.3, I get the error below when I installed Adanet on a VM from GCE

`ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/usr/.local/lib/python3.5/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.`

**Comment by MajesticKhan** [comment]
@cweill Submitted the PR...there is an additional issue which is related to the temp_dir_folder, however I will open up a separate issue on that and close this one once the changes are confirmed for deserializing the architecture file.

**Comment by LakeCarrot** [comment]
@MajesticKhan @cweill 
Note: I was running the following tutorial on Ubuntu 16.04, with Tensorflow 1.13, Python 3.5 and numpy 1.16.4.
[https://github.com/tensorflow/adanet/blob/master/adanet/examples/tutorials/customizing_adanet.ipynb](url)

I met the same problem (see the attached file for detailed error log)
The specific code snippet I tried to run is as follows, 
```
#@test {"skip": true}
#@title Parameters
LEARNING_RATE = 0.003  #@param {type:"number"}
TRAIN_STEPS = 5000  #@param {type:"integer"}
BATCH_SIZE = 64  #@param {type:"integer"}
ADANET_ITERATIONS = 2  #@param {type:"integer"}

estimator = adanet.Estimator(
    head=head,
    subnetwork_generator=simple_dnn.Generator(
        feature_columns=feature_columns,
        optimizer=tf.train.RMSPropOptimizer(learning_rate=LEARNING_RATE),
        seed=RANDOM_SEED),
    max_iteration_steps=TRAIN_STEPS // ADANET_ITERATIONS,
    evaluator=adanet.Evaluator(
        input_fn=input_fn("train", training=False, batch_size=BATCH_SIZE),
        steps=None),
    config=make_config("simple_dnn"))

results, _ = tf.estimator.train_and_evaluate(
    estimator,
    train_spec=tf.estimator.TrainSpec(
        input_fn=input_fn("train", training=True, batch_size=BATCH_SIZE),
        max_steps=TRAIN_STEPS),
    eval_spec=tf.estimator.EvalSpec(
        input_fn=input_fn("test", training=False, batch_size=BATCH_SIZE),
        steps=None,
        start_delay_secs=1,
        throttle_secs=1,  
    ))
print("Accuracy:", results["accuracy"])
print("Loss:", results["average_loss"])
```
It seems to me that updating the numpy version to 1.16.4 cannot work well. I wonder do you have any idea how to deal with this problem?

Detailed Error Log: [error.log](https://github.com/tensorflow/adanet/files/3257720/error.log)

**Comment by MajesticKhan** [comment]
@LakeCarrot ,

Running the latest version of numpy is not the issue. The error that you are seeing is related to `ensemble_arch = json.loads(serialized_architecture)`, please see the first post for further details.

Essentially, the serialized_architecture is in byte format when it should be in string format. However, this implies that you are running python 3.5 or lower as reading the documentation for python 3.6+ shows that `json.loads()` can take in bytes as inputs. 

See the links below:

-[`json.loads()`](https://docs.python.org/3.5/library/json.html) on python 3.5

-[`json.loads()`](https://docs.python.org/3.6/library/json.html) on python 3.6 

Credit goes to [Ikar Pohorský](https://stackoverflow.com/questions/42683478/typeerror-the-json-object-must-be-str-not-bytes/42683509) for spotting the [updates to `json.loads()`](https://docs.python.org/3/whatsnew/3.6.html#json) in python 3.6

**Comment by LakeCarrot** [comment]
@MajesticKhan ,
Thanks a lot for your replay. Yeah. after updating python from 3.5 to 3.6, problem solved. The problem is because of json.loads() function.
