### ISSUE TITLE
Error building adanet using bazel from source with protobuf version 3.6.0

### ISSUE THREAD

**Issue by chandramoulirajagopalan** [tensorflow/adanet#110]
https://github.com/bazelbuild/bazel/issues/6984#issuecomment-449315610
The link says the version is not compatible with bazel 0.21.0 . So the workspace version must be updated to 3.6.1.3

**Comment by cweill** [comment]
@chandramoulirajagopalan: Do you mind sending a PR to do so? I'll be happy to review it. 

We are looking to drop our requirements for protobuf and Bazel in the future to simplify installation.

**Comment by chandramoulirajagopalan** [comment]
Yes I will submit a PR as quick as possible.

**Comment by cweill** [comment]
Fixed with #111.
