### ISSUE TITLE
how to do early stopping while training adanet

### ISSUE THREAD

**Issue by guoqingyu319** [tensorflow/adanet#112]
When using adanet on my own data,I face a overfitting problem. I have to try to add early stopping strategy while training adanet.My problem is early stopping strategy stop the adanet iteration.So How can I do early stopping in each iteration so that I can solve the overfitting problem.
1.I set 8 iterations,each iteration has 200000 step
2.The whole training stop at 160000 step in first iteration,

![image](https://user-images.githubusercontent.com/22190680/58927498-6960e700-8781-11e9-9a73-da6c8ecfb2dd.png)

**Comment by cweill** [comment]
@guoqingyu319: We don't yet support early stopping per iteration, though it's something we would like to add. For now, the best thing is to set the `max_iteration_steps` to the right number to prevent overfitting (though sometime a little overfitting is good for the ensemble performance).

**Comment by guoqingyu319** [comment]
@cweill thanks a lot.In our scenario,we wanna use adanet to do automl.The biggest problem is some hyperparameters in adanet such as max_iteration_steps can not be automated completly.Different datasets have different max_iteration_steps we need.So the right number you said is also a parameter we should try.Thank you so much!

**Comment by cweill** [comment]
@guoqingyu319 What we generally do is tune the train steps (i.e. number of epochs) to find the best AdaNet model.
