### ISSUE TITLE
Failing tutorial adanet_tpu.ipynb during evaluation

### ISSUE THREAD

**Issue by lc0** [tensorflow/adanet#123]
Unfortunately an example adanet_tpu.ipynb has failed on me.

it fails with a bunch of stack traces, please find more details in attached document. One from the top is 

```
AbortedError: Session 5a5ab9da26cfbcc9 is not found.
```

https://colab.research.google.com/drive/1MM5EpwS0j4VQkDIcaQ7qNU71Nrfo3-cL#scrollTo=-Fhi1SjkzVBt

**Comment by cweill** [comment]
@lc0 Thanks for reporting this. We'll have a look.

**Comment by EugenHotaj** [comment]
Hi @lc0, the Aborted Error seems spurious. If you look at the log a few lines up see some other errors about evaluation steps "steps" not being set on TPU.

![image](https://user-images.githubusercontent.com/6221162/65047193-04945b80-d930-11e9-8dad-5e046b5359b6.png)

On TPU you must explicitly set the number of eval steps to run and unfortunately cannot rely on StopIteration exceptions to stop evaluating.

**Comment by lc0** [comment]
@EugenHotaj yeah, I also was thinking about this part. It's part of tutorial, I wonder how did it work before without explicit steps.

In any case we should update the tutorial to get it back to working state.

**Comment by EugenHotaj** [comment]
Oh I see what you're saying now. Yea the notebook was written before we supported evaluating on TPU and would always eval on CPU (in which case you don't need to specify the steps). I'll update the notebook. Good catch!

**Comment by lc0** [comment]
@cweill since the fix is in code itself, what is the cycle of release? it would be fixed in the next version right? shall we bump a version?

**Comment by cweill** [comment]
@lc0 We'll prepare release `v0.8.0` shortly; probably next week. Stay tuned! :)

**Comment by cweill** [comment]
@lc0 `v0.8.0` was just released. Please upgrade with `pip install adanet -U`, and let us know if it fixes your issue.

**Comment by lc0** [comment]
> @lc0 `v0.8.0` was just released. Please upgrade with `pip install adanet -U`, and let us know if it fixes your issue.

yeah, updated tutorial version with default `eval_on_tpu=True` works perfectly

**Comment by EugenHotaj** [comment]
Glad to hear that! Please keep opening issues against us if you run into more issues.
