### ISSUE TITLE
tf.Session(config=..) always takes all of the memory even through I set up the gpu_options

### ISSUE THREAD

**Issue by eustomaqua** [tensorflow/adanet#127]
Problem: gpu_options doesn't work. 
I used the codes in AdaNet like
```python
GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)
sess = tf.Session(config = CONFIG)
```

But it still occupied the whole gpu memory when I run the AdaNet. For example:
(1) If there is only 4G memory left, it will occupied the remaining 6G memory
(2) If there is no other process occupying the GPU memory (i.e., there is 10G memory left), it will occupied the whole 10G memory when I run the AdaNet.
So I think it doesn't need 10G to run but it takes that much any way.

I expect it only takes the memory it needs, instead of taking all of them. Therefore, I could make use of the 10G GPU memory better.
But now, I have no idea how to fix this issue. Could anybody please give me some suggestions? Thanks a lot.

Other system information:
- Ubuntu 16.04 and Ubuntu 18.04
- Python 3.6
- TensorFlow-gpu 1.12 and TensorFlow-gpu 1.14
- tf 1.12 with cuda 9, tf 1.14 with cuda10

**Comment by cweill** [comment]
Fixed by #133
