### ISSUE TITLE
Tutorials need to be updated to work with TensorFlow 2.0

### ISSUE THREAD

**Issue by zhiqwang** [tensorflow/adanet#130]
Hi, Thanks for your cool work.
But the tutorial of adanet (vesion 0.8.0) seems incompatible with tensorflow 2.0, would you please add more tutorials here?

**Comment by cweill** [comment]
@zhiqwang: You're right, we need to update our tutorials to use TF 2.

**Comment by cweill** [comment]
This should be relatively easy to port over, using `tf.compat.v1` for missing modules.

**Comment by EmielSchmeink** [comment]
As per [this](https://www.tensorflow.org/guide/upgrade#compatibility_modules), you should try to use the new modules instead of using compat.v1 everywhere.

**Comment by cweill** [comment]
This should be resolved now.
