### ISSUE TITLE
Candidate evaluations on TPU

### ISSUE THREAD

**Issue by jankrynauw** [tensorflow/adanet#131]
The current `eval_on_tpu` parameter passed to the estimator only applies to the `estimator.evaluate()` method and has no effect on the `evaluator` used to evaluate candidates:
```
evaluator = adanet.Evaluator(input_fn=evaluation_input_fn, steps=None)
...
estimator = adanet.TPUEstimator(
        head=head,
        ...
        evaluator=evaluator,
        eval_on_tpu=true,
       ...
    )
```
This currently has no relevance to the candidate evaluations as they are hard-coded to happen on CPU when Adanet decides which candidate to select to move on to the next iteration.

The TPUs therefore have to wait for the CPUs to do the candidate evaluations, and the CPUs have to wait for the TPUs to train the models.  Is candidate evaluations on CPUs not introducing a fairly significant bottleneck?

Here are a few example stats on running Adanet on TPUs confirming the above:
**CPUs:**
![CPU Stats](http://files.alis.fund/images/gitter/cpu-stats.png)

**TPUs**
![TPU CPU](http://files.alis.fund/images/gitter/tpu-cpu.png)
![TPU Memory](http://files.alis.fund/images/gitter/tpu-memory.png)
![TPU Network](http://files.alis.fund/images/gitter/tpu-network.png)

@EugenHotaj mentioned that this hard-coding was necessary based on how previous versions of AdaNet were implemented that they have since moved away from. Looking at the code now, there doesn't seem to be any fundamental reason why they need to evaluate on CPU during the candidate evaluation phase.

**Comment by cweill** [comment]
@jankrynauw  We just released adanet=0.9.0 which includes better TPU, and TF 2 support. Please try installing it, and let us know if it resolves your issue.
