### ISSUE TITLE
Colaboratory Notebooks for the tutorials

### ISSUE THREAD

**Issue by xhlulu** [tensorflow/adanet#14]
I noticed that for the [Jupyter Notebook tutorials](https://github.com/tensorflow/adanet/tree/master/adanet/examples/tutorials), there wasn't any corresponding Colaboratory notebook. It would be nice to have them for quickly getting started and for beginners, since setting up the notebooks locally require a lot of steps (install cuda, update protoc, update protobuf, etc.)

Would it be reasonable to add them? If so, I'd be happy to start a PR, if it's logistically possible.

Thank you!

**Comment by cweill** [comment]
@xhlulu: That would be most welcome. Could you please add links to Colab and GitHub in the notebooks similar to how [TensorFlow does it](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/eager/python/examples/notebooks/custom_layers.ipynb).
