### ISSUE TITLE
relation to AutoML tables in GCP

### ISSUE THREAD

**Issue by 4d55397500** [tensorflow/adanet#145]
@cweill, apologize if this is a naive question, but how does/where can I find out how this codebase relate to what's exposed as 'AutoML tables' in Google Cloud Platform?

**Comment by EugenHotaj** [comment]
Hi @4d55397500,

AdaNet is used as one of the models in AutoML Tables in GCP. So the final model returned by AutoML tables may be an AdaNet model if it was found to outperform the other models. You can find out more [here](https://cloud.google.com/automl-tables/docs/features#model_training).

**Comment by 4d55397500** [comment]
I see, thanks @EugenHotaj , it's one of the possible models
