### ISSUE TITLE
WARNING:tensorflow:Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.

### ISSUE THREAD

**Issue by picarus** [tensorflow/adanet#37]
Hello,
I am using tf 1.11 and tft 0.11 with Adanet 0.4 (but also happened with 0.3). I am getting the warning:

WARNING:tensorflow:Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.

A bit of search has taken me to:
https://stackoverflow.com/questions/50850258/tensorflow-estimator-switching-to-careful-interpolation-to-get-the-correct-pr-a/51288757

I have tried to implement this calling on  the object obtained from adanet.Estimator but I receive an error saying the estimator object can not be directly called.

Any suggestions on how to solve the problem or avoid it in the first place?
I am using a modification of the adanet_objective example just changing it to use other data (the Criteo dataset) so, I don't really understand why the warning appears because it doesn't when I run the original example.

**Comment by svjack** [comment]
> Hello,
> I am using tf 1.11 and tft 0.11 with Adanet 0.4 (but also happened with 0.3). I am getting the warning:
> 
> WARNING:tensorflow:Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
> 
> A bit of search has taken me to:
> https://stackoverflow.com/questions/50850258/tensorflow-estimator-switching-to-careful-interpolation-to-get-the-correct-pr-a/51288757
> 
> I have tried to implement this calling on the object obtained from adanet.Estimator but I receive an error saying the estimator object can not be directly called.
> 
> Any suggestions on how to solve the problem or avoid it in the first place?
> I am using a modification of the adanet_objective example just changing it to use other data (the Criteo dataset) so, I don't really understand why the warning appears because it doesn't when I run the original example.

add_metrics init a estimator use base class Estimator in tensorflow rather than adanet.

**Comment by picarus** [comment]
Yep, I found that just after I submitted the issue.
But my key point here is why the issue happens when I change the dataset if it does not happen with the original  data in the same environment.

**Comment by cweill** [comment]
Are you using `tf.contrib.estimator.binary_classification_head`? I think it's an issue with one of the metrics in there, so it's not unique to adanet.

**Comment by picarus** [comment]
Thanks! Totally right!
