### ISSUE TITLE
 Failed to get device properties, error code: 30

### ISSUE THREAD

**Issue by Mingqi-Yuan** [tensorflow/adanet#53]
When I use the **GTX 1050 Ti** to train the adanet，the error appers like this：

**2018-12-27 13:21:33.808781: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30**

### Here are my code：
import adanet
import tensorflow as tf
import data_input
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

feature_columns = [tf.feature_column.numeric_column('features', shape = [224, 224, 3])]

head = tf.contrib.estimator.binary_classification_head()

estimator = adanet.AutoEnsembleEstimator(
    head=head,
    candidate_pool=[
        tf.contrib.estimator.LinearEstimator(
            head=head,
            feature_columns=feature_columns,
            optimizer=tf.train.AdamOptimizer(0.01)),
        tf.contrib.estimator.DNNEstimator(
            head=head,
            feature_columns=feature_columns,
            optimizer=tf.train.AdamOptimizer(0.01),
            hidden_units=[1000, 500, 100]),
        tf.contrib.estimator.DNNEstimator(
            head=head,
            feature_columns=feature_columns,
            optimizer=tf.train.AdamOptimizer(0.01),
            hidden_units=[500])
    ],
    max_iteration_steps=1000,
    model_dir=r"C:\Users\12420\Desktop\Chest X-Ray Automatic Identification\result"
)

estimator.train(input_fn=data_input.input_fn('training', 5), max_steps= 10000)

 How can I solve this problem？I‘d appreciate much if you can help me with this！

**Comment by cweill** [comment]
Do you get this error if you replace `adanet.AutoEnsembleEstimator` with just`tf.contrib.estimator.DNNEstimator`?

**Comment by abtExp** [comment]
Facing the same issue while training ENet on Flikr47 dataset on a nvidia gtx 1050ti.
TensorFlow version 1.12.0

**Comment by cweill** [comment]
@abtExp: Please see my previous comment.

**Comment by abtExp** [comment]
@cweill I'm not using adanet, I'm simply using keras .
I implemented ENet in keras and while training it, it throws this error.

**Comment by cweill** [comment]
This sounds like a TensorFlow issue. Please reach out to them.
