### ISSUE TITLE
[Question]distrubute training

### ISSUE THREAD

**Issue by tianxh1212** [tensorflow/adanet#54]
Hi,
I have used two GPUs for distributed training, using a custom subnet. and it works well when using single GPU to run. but there is an error when using Multiple GPUs by `distribution = tf.contrib.distribute.MirroredStrategy()`

`2018-12-29 03:48:10.474563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 14874 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2018-12-29 03:48:10.474844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:1 with 14874 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0000:32:00.0, compute capability: 7.0)
INFO:tensorflow:A GPU is available on the machine, consider using NCHW data format for increased speed on GPU.
INFO:tensorflow:Error reported to Coordinator: No variables to optimize.
Traceback (most recent call last):
  File "/root/anaconda3/envs/tianxh_py36/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/root/anaconda3/envs/tianxh_py36/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 797, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/root/anaconda3/envs/tianxh_py36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/tianxh/AdaNet/adanet/core/estimator.py", line 1121, in _adanet_model_fn
    previous_ensemble_spec=previous_ensemble_spec)
  File "/home/tianxh/AdaNet/adanet/core/iteration.py", line 257, in build_iteration
    labels=labels)
  File "/home/tianxh/AdaNet/adanet/core/ensemble.py", line 526, in append_new_subnetwork
    previous_ensemble_spec=ensemble_spec)
  File "/home/tianxh/AdaNet/adanet/core/ensemble.py", line 663, in _build_ensemble_spec
    previous_ensemble=previous_ensemble))
  File "tianxh_test.py", line 301, in build_subnetwork_train_op
    return optimizer.minimize(loss, var_list=var_list)
  File "/root/anaconda3/envs/tianxh_py36/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 400, in minimize
    grad_loss=grad_loss)
  File "/root/anaconda3/envs/tianxh_py36/lib/python3.6/site-packages/tensorflow/contrib/estimator/python/estimator/extenders.py", line 303, in compute_gradients
    return self._optimizer.compute_gradients(*args, **kwargs)
  File "/root/anaconda3/envs/tianxh_py36/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 513, in compute_gradients
    raise ValueError("No variables to optimize.")`

it seems that the first thread is ok， the second thread can't get vars through tf.trainable_variables()
**var_list comes from adanet/core/ensemble.py line495**
`var_list = tf.trainable_variables()`

Could you please give some advice?
Thanks

**Comment by cweill** [comment]
@tianxh1212 : Thank you for noting this. I wasn't aware that the only way to do multi-GPU training with Estimator was with `tf.contrib.distribute`: https://github.com/tensorflow/models/issues/4774

MirroredStrategy [should not be creating multiple threads to create the graph](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/distribute/python/mirrored_strategy.py#L97). Lots of TF and AdaNet code is not threadsafe, so this would be an issue when creating the graph. I don't think there is a race condition here.

We haven't been testing with `tf.contrib.distribute` yet. If you find a simple solution, feel free to send a PR.

**Comment by tianxh1212** [comment]
> @tianxh1212 : Thank you for noting this. I wasn't aware that the only way to do multi-GPU training with Estimator was with `tf.contrib.distribute`: [tensorflow/models#4774](https://github.com/tensorflow/models/issues/4774)
> 
> MirroredStrategy [should not be creating multiple threads to create the graph](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/distribute/python/mirrored_strategy.py#L97). Lots of TF and AdaNet code is not threadsafe, so this would be an issue when creating the graph. I don't think there is a race condition here.
> 
> We haven't been testing with `tf.contrib.distribute` yet. If you find a simple solution, feel free to send a PR.

thanks very much， successfully ran distribute training by using TF_CONFIG.
https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate

**Comment by cweill** [comment]
Thank you for confirming that it works with TF_CONFIG.

**Comment by saikia1** [comment]
@tianxh1212 I have the same issue. Can you please share the TF_CONFIG` you have used to run the training?

**Comment by tianxh1212** [comment]
> @tianxh1212 I have the same issue. Can you please share the TF_CONFIG` you have used to run the training?
os.environ["TF_CONFIG"] = json.dumps({
            "cluster": {
                "chief": ["localhost:3224"],
                "ps": ["localhost:3222", "localhost:3223"],
                "worker": ["localhost:3225","localhost:3226","localhost:3227",
                           "localhost:3228", "localhost:3229", "localhost:3230"]
            },
            "task": {"type": "ps", "index": 0}
        })
os.environ["TF_CONFIG"] = json.dumps({
            "cluster": {
                "chief": ["localhost:3224"],
                "ps": ["localhost:3222", "localhost:3223"],
                "worker": ["localhost:3225","localhost:3226","localhost:3227",
                           "localhost:3228", "localhost:3229", "localhost:3230"]
            },
            "task": {"type": "chief", "index": 0}
        })
os.environ["TF_CONFIG"] = json.dumps({
            "cluster": {
                "chief": ["localhost:3224"],
                "ps": ["localhost:3222", "localhost:3223"],
                "worker": ["localhost:3225","localhost:3226","localhost:3227",
                           "localhost:3228", "localhost:3229", "localhost:3230"]
            },
            "task": {"type": "worker", "index": 0}
        })
os.environ["TF_CONFIG"] = json.dumps({
            "cluster": {
                "chief": ["localhost:3224"],
                "ps": ["localhost:3222", "localhost:3223"],
                "worker": ["localhost:3225","localhost:3226","localhost:3227",
                           "localhost:3228", "localhost:3229", "localhost:3230"]
            },
            "task": {"type": "evaluator", "index": 0}
        })

this is used for seven gpus on one server, one chief and six workers, you may change it according to your situation :-)
and this mode uses asynchronous gradient updates, i think

**Comment by saikia1** [comment]
@tianxh1212 thank you.
