### ISSUE TITLE
[Question] How to remove WARNING: `persisted_tensors` is deprecated, please use `shared` instead

### ISSUE THREAD

**Issue by shawpan** [tensorflow/adanet#59]
`WARNING:tensorflow:From //anaconda/envs/ws/lib/python3.6/site-packages/adanet/examples/simple_dnn.py:104: calling Subnetwork.__new__ (from adanet.core.subnetwork.generator) with persisted_tensors is deprecated and will be removed in a future version.
Instructions for updating:
`persisted_tensors` is deprecated, please use `shared` instead.
`

**Comment by cweill** [comment]
When creating an `adanet.subnetwork.Subnetwork`, instead of setting its `persisted_tensors` field, set `shared` instead.

**Comment by cweill** [comment]
@shawpan: Things have been moving pretty quickly, and we haven't had time to update `simple_dnn.Generator`. Feel free to send a PR with the fix, and I'll review it.

**Comment by shawpan** [comment]
Thanks, @cweill. I will send a PR. Is there any guideline to PR for this repository?

**Comment by shawpan** [comment]
fixed
