### ISSUE TITLE
module 'tensorflow.estimator' has no attribute 'LinearEstimator'

### ISSUE THREAD

**Issue by Sigm0oid** [tensorflow/adanet#62]
Running the exact same example in the Documentation lead to this error:

> **module 'tensorflow.estimator' has no attribute 'LinearEstimator'**
Any one here have any Idea how to solve this ?
Update : Tensoflow version =1.12.0

**Comment by Sigm0oid** [comment]
Solved by replacing  with : **tf.estimator.** with  **tf.contrib.estimator.**

**Comment by cweill** [comment]
Indeed, they currently live under `tf.contrib.estimator`.
