### ISSUE TITLE
Adanet in Keras gives ValueError: Tensor tensor_object is not found in checkpoint after warm-starting variable

### ISSUE THREAD

**Issue by shachi01** [tensorflow/adanet#67]
- Implemented adanet in Keras in building dense layers and setting up kernel_initializer.
- Successfully trained, evaluated and the best_candidate moved onto next iteration in Iteration-1, but before moving towards next iteration "warm-starting variable" section is giving an error as below.

**Error**
ValueError: Tensor adanet/iteration_0/ensemble_t0_2_layer_dnn/weighted_subnetwork_0/subnetwork/dense_1/kernel is not found in /home/ec2-user/SageMaker/logs/keras_ada_logs/model.ckpt-500 checkpoint {'adanet/iteration_0/train_op/is_over/is_over_var_fn/is_over_var': [], 'adanet/iteration_0/step': [], 'adanet/iteration_0/ensemble_t0_2_layer_dnn/weighted_subnetwork_0/subnetwork/dense_3/kernel': [99, 50] . . . }

**Error Stacktrace**

INFO:tensorflow:Warm-starting from: ('/home/ec2-user/SageMaker/logs/keras_ada_logs/model.ckpt-500',)
INFO:tensorflow:Warm-starting variable: global_step; prev_var_name: Unchanged
INFO:tensorflow:Warm-starting variable: adanet/iteration_0/step; prev_var_name: Unchanged
INFO:tensorflow:Warm-starting variable: adanet/iteration_0/ensemble_t0_2_layer_dnn/weighted_subnetwork_0/subnetwork/dense_1/kernel; prev_var_name: Unchanged
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-6d1781adf9c6> in <module>()
      1 #train and evaluate on default parameters
      2 
----> 3 results, _ = train_and_evaluate()

<ipython-input-15-3cb4c294b0ab> in train_and_evaluate(learn_mixture_weights, adanet_lambda)
     51       steps=None)

---> 53     return tf.estimator.train_and_evaluate(AdaNetEstimator, train_spec, eval_spec)
~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py in train_and_evaluate(estimator, train_spec, eval_spec)
    469         '(with task id 0).  Given task id {}'.format(config.task_id))
 
--> 471   return executor.run()
~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py in run(self)
    608         config.task_type != run_config_lib.TaskType.EVALUATOR):
    609       logging.info('Running training and evaluation locally (non-distributed).')
--> 610       return self.run_local()
    611 
    612     # Distributed case.

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py in run_local(self)
    709         max_steps=self._train_spec.max_steps,
    710         hooks=train_hooks,
--> 711         saving_listeners=saving_listeners)
    712 
    713     eval_result = listener_for_eval.eval_result or _EvalResult(

~/anaconda3/envs/python3/lib/python3.6/site-packages/adanet/core/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    499           # in order to use them when preparing the next iteration.
    500           self._train_hooks = hooks or ()
--> 501           self._prepare_next_iteration(input_fn)
    502 
    503         # This inner loop serves mainly for synchronizing the workers with the

~/anaconda3/envs/python3/lib/python3.6/site-packages/adanet/core/estimator.py in _prepare_next_iteration(self, train_input_fn)
    618     params[self._Keys.INCREMENT_ITERATION] = True
    619     self._call_adanet_model_fn(train_input_fn, tf.estimator.ModeKeys.TRAIN,
--> 620                                params)
    621 
    622   def _architecture_filename(self, iteration_number):

~/anaconda3/envs/python3/lib/python3.6/site-packages/adanet/core/estimator.py in _call_adanet_model_fn(self, input_fn, mode, params)
    578       tf.train.get_or_create_global_step()
    579       features, labels = input_fn()
--> 580       self._adanet_model_fn(features, labels, mode, params)
    581 
    582   def _prepare_next_iteration(self, train_input_fn):

~/anaconda3/envs/python3/lib/python3.6/site-packages/adanet/core/estimator.py in _adanet_model_fn(self, features, labels, mode, params)
   1102       if self._Keys.INCREMENT_ITERATION in params:
   1103         latest_checkpoint = tf.train.latest_checkpoint(self.model_dir)
-> 1104         tf.train.warm_start(latest_checkpoint, vars_to_warm_start=[".*"])
   1105       previous_ensemble_reports, all_reports = [], []
   1106       if self._report_materializer:

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/warm_starting_util.py in warm_start(ckpt_to_initialize_from, vars_to_warm_start, var_name_to_vocab_info, var_name_to_prev_var_name)
    461         if len(variable) == 1:
    462           variable = variable[0]
--> 463         _warm_start_var(variable, ckpt_to_initialize_from, prev_var_name)
    464 
    465   prev_var_name_not_used = set(

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/warm_starting_util.py in _warm_start_var(var, prev_ckpt, prev_tensor_name)
    179     # Assume tensor name remains the same.
    180     prev_tensor_name = current_var_name
--> 181   checkpoint_utils.init_from_checkpoint(prev_ckpt, {prev_tensor_name: var})

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py in init_from_checkpoint(ckpt_dir_or_file, assignment_map)
    185   else:
    186     distribution_strategy_context.get_tower_context().merge_call(
--> 187         _init_from_checkpoint, ckpt_dir_or_file, assignment_map)

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/distribute.py in merge_call(self, merge_fn, *args, **kwargs)
   1051     """
   1052     require_tower_context(self)
-> 1053     return self._merge_call(merge_fn, *args, **kwargs)
   1054 
   1055   def _merge_call(self, merge_fn, *args, **kwargs):

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/distribute.py in _merge_call(self, merge_fn, *args, **kwargs)
   1059             self._distribution_strategy))
   1060     try:
-> 1061       return merge_fn(self._distribution_strategy, *args, **kwargs)
   1062     finally:
   1063       _pop_per_thread_mode()

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py in _init_from_checkpoint(_, ckpt_dir_or_file, assignment_map)
    214       if tensor_name_in_ckpt not in variable_map:
    215         raise ValueError("Tensor %s is not found in %s checkpoint %s" % (
--> 216             tensor_name_in_ckpt, ckpt_dir_or_file, variable_map
    217         ))
    218       if _is_variable(var):

**Comment by cweill** [comment]
@shachi01: I've also noticed this behavior with `tf.keras.layers`, due to how Keras layers interact with variable scoping. The best fix for now would be to use `tf.layers` equivalents instead, since they behave correctly. 

We'll try to add the correct support for Keras layers in a future AdaNet release.

**Comment by shachi01** [comment]
Thanks fir your response @cweill .
