### ISSUE TITLE
`from adanet.examples import simple_dnn` raises exception

### ISSUE THREAD

**Issue by cweill** [tensorflow/adanet#7]
Stack-trace when installing from pypi. See #3. 

In [customizing_adanet notebook](https://colab.research.google.com/drive/1Qf-pfBrNaMTmaPs3qZ16CyNy9p20drBc#scrollTo=x_3b6xx2s6B9), when doing `!pip install adanet` and then `from adanet.examples import simple_dnn`

```
ImportErrorTraceback (most recent call last)
<ipython-input-2-ef5cc5f68dee> in <module>()
      6 
      7 import adanet
----> 8 from adanet.examples import simple_dnn
      9 import tensorflow as tf
     10 

ImportError: No module named examples
```

**Comment by cweill** [comment]
This is now resolved in PyPi. Please upgrade your pip installation to at least `adanet-0.1.0.dev2`.

**Comment by zhouhao-learning** [comment]
@cweill 
I upgraded my pip, then I executed `pip install adanet-0.1.0.dev2` and could not find the correct package, and your github did not have the `adanet-0.1.0.dev2` branch. How should I solve this problem?

**Comment by cweill** [comment]
@zhouhao-learning: You will need to run `pip install adanet==0.1.0.dev2` to download the new package from from [Pypi](https://pypi.org/project/adanet/0.1.0.dev2/).

I have the changes ready but they are not yet pushed to this repository. You won't be able to use `adanet.examples` when installing from source with pip just yet. In the meantime you can install as described above.

**Comment by Bjoux2** [comment]
pip3 install --upgrade adanet
