### ISSUE TITLE
[Question] Assertion error using MirroredStrategy

### ISSUE THREAD

**Issue by shawpan** [tensorflow/adanet#76]
What is the actual reason for this error?

```
INFO:tensorflow:Error reported to Coordinator: 
Traceback (most recent call last):
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/adanet/core/estimator.py", line 1121, in _adanet_model_fn
    previous_ensemble_spec=previous_ensemble_spec)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/adanet/core/iteration.py", line 261, in build_iteration
    summary=summary)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/adanet/core/candidate.py", line 145, in build_candidate
    decay=self._adanet_loss_decay)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py", line 84, in assign_moving_average
    with ops.colocate_with(variable):
  File "//anaconda/envs/ws/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "//anaconda/envs/ws/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "//anaconda/envs/ws/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

The code for estimator  is given below

```
    distribution_strategy = tf.contrib.distribute.MirroredStrategy()
    runConfig = tf.estimator.RunConfig(
        train_distribute=distribution_strategy,
        eval_distribute=distribution_strategy,
        save_checkpoints_steps=100,
        save_summary_steps=100,
        tf_random_seed=RANDOM_SEED)
    estimator = adanet.Estimator(
        model_dir = OUTPUT_DIR,
        # metric_fn=custom_metrics,
        # adanet_loss_decay=0.99,
        head=tf.contrib.estimator.multi_label_head(
            name="name",
            n_classes=len(CONFIG['LABELS']),
            # classes_for_class_based_metrics= [5,6]
        ),
        subnetwork_generator=simple_dnn.Generator(
            learn_mixture_weights=True,
            dropout=CONFIG["DROPOUT"],
            feature_columns=get_feature_columns(),
            optimizer=tf.train.AdamOptimizer(learning_rate=ADANET_LEARNING_RATE),
            seed=RANDOM_SEED),
        max_iteration_steps=NUM_EPOCHS // ADANET_ITERATIONS,
        evaluator=adanet.Evaluator(
            input_fn=lambda : validation_input_fn(batch_size=BATCH_SIZE, num_epochs=NUM_EPOCHS),
            steps=EVAL_STEPS),
        config=runConfig)
```

The code runs without the distribution strategy configuration.

**Comment by shawpan** [comment]
adanet uses 
```
tensorflow.python.training.moving_averages
in candidate.py for "update_adanet_loss_op"
which passes variable as a reference but it is not allowed in mirrored distribution strategy 
```
in summary, it is not compatible with MirroredStrategy

upgraded tensorflow to 1.13.1 but now getting 
```
ValueError: You must specify an aggregation method to update a MirroredVariable in Replica Context.

which is in iteration.py for training_op
```
is adanet compatible with distribution strategies? if not, can it be made compatible without major change?
@cweill it would be a great help if you give some insight

**Comment by cweill** [comment]
@shawpan: We haven't tested AdaNet with distribution strategies, since they are still in `tf.contrib`, so we don't officially support them yet. What is it you are trying to do with `MirroredStrategy`?

**Comment by shawpan** [comment]
I am trying to test a multi-label classifier implemented with adanet to run on multi-gpu. Distribution strategies looked like the easiest implementation so I am trying with `MirroredStrategy`. The target is to make it work with a variable number of machines and gpu so that the training finishes within the expected duration. How can it be done using adanet?

**Comment by cweill** [comment]
Since we don't yet support tf.distribution strategies, have a look at #54. They use a TF_CONFIG for distributed training, and that we support. Are you using adanet HEAD or Pypi's v0.5.0? master branch includes several distributed training fixes that will only be available once we release v0.6.0.

**Comment by shawpan** [comment]
Thanks, Charles, I am using the 0.5 release. Will try with master and TF_CONFIG set up.

**Comment by shawpan** [comment]
with `TF_CONFIG`,  it waits forever on this line, 
```
2019-03-18 11:31:10.910716: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:2225
```
also, there are mismatches in tf documentation. cluster spec says the task type can be master, ps and worker where the examples are written as chief, ps and worker. I am posting the `TF_CONFIG` below. Tried several combinations. It might be a simple mistake from my side.
```
{
    "task": {
      "type": "ps",
      "index": 0
    },
    "cluster": {
      "master": ["localhost:2222"],
      "worker": ["localhost:2223"],
      "ps": ["localhost:2225"]
    }
  }
```
or
```
{
    "task": {
      "type": "ps",
      "index": 0
    },
    "cluster": {
      "master": ["localhost:2222"],
      "worker": ["localhost:2223"],
      "ps": ["localhost:2225"]
    },
    "model_dir": "/tmp/model_output",
    "environment": "cloud"
  }
```
or
```
{
    "task": {
      "type": "ps",
      "index": 0
    },
    "cluster": {
      "chief": ["localhost:2222"],
      "worker": ["localhost:2223"],
      "ps": ["localhost:2225"]
    }
  }
```

**Comment by SmallyolkLiu** [comment]
Hi, @shawpan
I have the same question. I have a small workstation with two pieces of GTX 1080 GPUs, so I hope to train a model on AdaNet in parallel, but it seems not support. Do you find an effective solution to do this?

**Comment by shawpan** [comment]
Ok my bad, I misunderstood the `TF_CONFIG` settings. Looks fine for now on my side (local, CPU). Will try on GPU multi hosts later. @SmallyolkLiu yes, I will post a detailed example so that others like you and me can work with the solution. Let me write the example properly and I will get back.

**Comment by EugenHotaj** [comment]
Hi @SmallyolkLiu,

If the GPUs you are trying to run on are on your local workstation, you do not need to run in distributed mode. Tensorflow should automatically assign ops to the GPUs: https://www.tensorflow.org/guide/using_gpu

**Comment by shawpan** [comment]
I have added a quick example/boilerplate code that shows how to use `TF_CONFIG`. It may help others. https://github.com/shawpan/adanet-examples/tree/master/distributed_training

Please note that here I have skipped `data.py` and `config.py` files that anybody can add according to their own need and does not relate to distributed training. I will add them with an example dataset later. @SmallyolkLiu

**Comment by shawpan** [comment]
Closing the issue because adanet does not support distribution strategies yet so this kind of error is likely.
