### ISSUE TITLE
Inconsistency in overriding method?

### ISSUE THREAD

**Issue by SmallyolkLiu** [tensorflow/adanet#84]
https://github.com/tensorflow/adanet/blob/db6f5b65436d7a5ccbb49ec4967ed2314f2a86fa/adanet/examples/nasnet.py#L82

Using pycharm to open nasnet.py, showing that:
Signature of method '_NASNet.build_subnetwork' does not match signature of base method in class Builder

dose this mean the inconsistency in overriding method?

**Comment by cweill** [comment]
The superclass is an abstract class, and in Python abstractmethods like `build_subnetwork` do not require their arguments to match the parent's signature. AdaNet will call the method with kwargs if they are there, so the user can use whatever subset of the arguments they need.
