### ISSUE TITLE
TensorFlow 1 & 2 Support

### ISSUE THREAD

**Issue by ushmalramesh** [tensorflow/adanet#93]
Currently importing adanet with tensorflow 2.0.0alpha gives the error 'ModuleNotFoundError: No module named 'tensorflow.contrib''

Are there plans to extend compatibility to the new TF API?

**Comment by cweill** [comment]
@ushmalramesh: We'll be adding TF 2.0 support slowly but surely over the next few months, but don't expect full TF 2.0 until end-of-summer '19 and once TF 2.0 is out of pre-release.

**Comment by cweill** [comment]
Fixed in `adanet==0.8.0` release.

**Comment by lc0** [comment]
@cweill does it mean, that now we can test adanet with tf2?

**Comment by shendiaomo** [comment]
> @cweill does it mean, that now we can test adanet with tf2?

I don't think so because it seems that adanet.Estimator still depends on contrib.Head,

**Comment by cweill** [comment]
@lc0 Yes, you should now be able to test TF2. @shendiaomo: AdaNet currently supports the new estimator heads, such as `tf.estimator.RegressionHead()` and `tf.estimator.BinaryClassHead()`.
